apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
  labels:
    app: sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
        - name: sample
          image: hcwtestregistry01.azurecr.io/tomcatsample-aks
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sample-cluster-svc
  labels:
    app: sample
spec:
  type: ClusterIP
  ports:
   - name: http-8080
     port: 8080
     protocol: TCP
     targetPort: 8080  
  selector:
   app: sample
   
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: samplelegacy-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: sample-aks-cicd.com
    http:
      paths:
      - backend:
          service:
            name: sample-cluster-svc
            port:
              number: 8080
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - sample-aks-cicd.com
    secretName: sample-ingress-tls
